### ISSUE TITLE
install problem

### ISSUE THREAD

**Issue by amElliotCheung** [liborui/WAIT#1]
Sorry, I want to try your WAIT on microcontrollers but I cannot install it. 

I have an Ubuntu 20.04 and downloaded all the dependencies
I didn't understand this sentence in README.md
```
Go into libs folder
```
Where is libs folder?

**Comment by liborui** [comment]
Sorry for the late reply!
If you have any further questions on WAIT, feel free to re-open this issue.

**Comment by amElliotCheung** [comment]
Sorry, I closed the issue yesterday because I didn't describe it clearly.

I try to describe my workflow clearly this time.

First, I cloned your repository and installed the dependencies. Everything was ok.
```
~/ git clone https://github.com/liborui/WAIT
~/ apt install git build-essential wget curl unzip gcc-multilib xxd cmake wabt python3
~/ apt install gcc-avr avr-libc avrdude gdb-avr openjdk-11-jdk
```

Then I downloaded and unzipped the wasi-sdk. But I didn't find the *libs* folder. So I tried to put it into the *third-party* folder
```
The WASI SDK should reside in the *libs/wasi-sdk-12.0* folder.
```

Finally I encountered the problem.
I executed these commands in ~/WAIT
```
~/WAIT rm -rf build
~/WAIT mkdir build&&cd build
~/WAIT/build cmake ..
~/WAIT/build make
```
I got error
```
/root/WAIT/src/main.c:1:23: fatal error: test.wasm.h: No such file or directory
compilation terminated.
```

I'm guessing something is wrong with my file structure. I beg your help.

**Comment by liborui** [comment]
> Sorry, I closed the issue yesterday because I didn't describe it clearly.
> 
> I try to describe my workflow clearly this time.
> 
> First, I cloned your repository and installed the dependencies. Everything was ok.
> 
> ```
> ~/ git clone https://github.com/liborui/WAIT
> ~/ apt install git build-essential wget curl unzip gcc-multilib xxd cmake wabt python3
> ~/ apt install gcc-avr avr-libc avrdude gdb-avr openjdk-11-jdk
> ```
> 
> Then I downloaded and unzipped the wasi-sdk. But I didn't find the _libs_ folder. So I tried to put it into the _third-party_ folder
> 
> ```
> The WASI SDK should reside in the *libs/wasi-sdk-12.0* folder.
> ```
> 
> Finally I encountered the problem. I executed these commands in ~/WAIT
> 
> ```
> ~/WAIT rm -rf build
> ~/WAIT mkdir build&&cd build
> ~/WAIT/build cmake ..
> ~/WAIT/build make
> ```
> 
> I got error
> 
> ```
> /root/WAIT/src/main.c:1:23: fatal error: test.wasm.h: No such file or directory
> compilation terminated.
> ```
> 
> I'm guessing something is wrong with my file structure. I beg your help.

This error is mainly because there lack of a WASM module  to be executed by WAIT. I will back to you when I put a upgrade on this problem.

**Comment by amElliotCheung** [comment]
Thank you very much!
Looking forward to the upgrade!!

**Comment by liborui** [comment]
Hi!
To use WAIT, you should have a WebAssembly module. We internally provided a WebAssembly hello-world module which resides in the `example` folder. You should first compile the WebAssembly module (to get a `xxxx.wasm.h`), and introduce it to the `src/main.c`.

The older version of the README is vague, and I have fixed the issue by
[19644d1](https://github.com/liborui/WAIT/commit/19644d1a22efef687fbea4da082c14c49792f522)

You can try it out!
If you have further questions, feel free to reopen this issue!

**Comment by amElliotCheung** [comment]
Hi~
it ran successfully
Thanks for your prompt reply and help 😄
